// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxKNjlUHinu6YGgFU-l3WZj6vJtp-93xE',
    appId: '1:661259751025:web:90adc0f1e59c969ac995d0',
    messagingSenderId: '661259751025',
    projectId: 'fyp-hub-affe3',
    authDomain: 'fyp-hub-affe3.firebaseapp.com',
    storageBucket: 'fyp-hub-affe3.firebasestorage.app',
    measurementId: 'G-NJE9KE6XNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqgb9zWzfVOqcVeVhlJajB0QLBxIXHSyQ',
    appId: '1:661259751025:android:e22dff49a673c567c995d0',
    messagingSenderId: '661259751025',
    projectId: 'fyp-hub-affe3',
    storageBucket: 'fyp-hub-affe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG3EY7JqJa73Voin8-ArC9qAIOgX5hfjI',
    appId: '1:661259751025:ios:042a96eeada0ddf1c995d0',
    messagingSenderId: '661259751025',
    projectId: 'fyp-hub-affe3',
    storageBucket: 'fyp-hub-affe3.firebasestorage.app',
    iosBundleId: 'com.example.fypHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG3EY7JqJa73Voin8-ArC9qAIOgX5hfjI',
    appId: '1:661259751025:ios:042a96eeada0ddf1c995d0',
    messagingSenderId: '661259751025',
    projectId: 'fyp-hub-affe3',
    storageBucket: 'fyp-hub-affe3.firebasestorage.app',
    iosBundleId: 'com.example.fypHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxKNjlUHinu6YGgFU-l3WZj6vJtp-93xE',
    appId: '1:661259751025:web:7dc90b6e434f70d1c995d0',
    messagingSenderId: '661259751025',
    projectId: 'fyp-hub-affe3',
    authDomain: 'fyp-hub-affe3.firebaseapp.com',
    storageBucket: 'fyp-hub-affe3.firebasestorage.app',
    measurementId: 'G-DL6KQGFJH4',
  );
}
