// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // Generated by flutterfire
// import 'package:fyp_hub/screens/wrapper.dart'; // Ensure this file exists

// void main() async {
//   // 1. Ensure Flutter is initialized
//   WidgetsFlutterBinding.ensureInitialized();

//   // 2. Initialize Firebase
//   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

//   // 3. Run your app
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       debugShowCheckedModeBanner: false,
//       title: 'FYP Hub',
//       theme: ThemeData(
//         brightness: Brightness.dark,
//         colorScheme: ColorScheme.fromSeed(
//           seedColor: Colors.blue,
//           brightness: Brightness.dark,
//         ),
//         useMaterial3: true,
//       ),
//       // 4. THE FIX: Point to Wrapper.
//       // This will check if you are logged in.
//       // If not, it sends you to Login. If yes, it sends you to Home.
//       home: const Wrapper(),
//     );
//   }
// }

import 'package:flutter/material.dart'; // Standard import is fine now
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:fyp_hub/screens/wrapper.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // --- PALETTE DEFINITION ---
    const nightCharcoal = Color(0xFF323643); // Text / Nav / Buttons
    const slateGrey = Color(0xFF606470); // Borders / Subtitles
    const iceBlue = Color(0xFF93DEFF); // Accents / Neon Glow
    const snowWhite = Color(0xFFF7F7F7); // Background

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FYP Hub',
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        scaffoldBackgroundColor: snowWhite,

        // --- COLOR SCHEME ---
        colorScheme: const ColorScheme.light(
          primary: nightCharcoal,
          onPrimary: iceBlue,
          secondary: iceBlue,
          onSecondary: nightCharcoal,
          surface: Colors.white,
          onSurface: nightCharcoal,
          error: Colors.redAccent,
        ),

        // --- TYPOGRAPHY ---
        textTheme: const TextTheme(
          displayLarge: TextStyle(
            color: nightCharcoal,
            fontWeight: FontWeight.bold,
          ),
          headlineLarge: TextStyle(
            color: nightCharcoal,
            fontWeight: FontWeight.bold,
          ),
          titleLarge: TextStyle(
            color: nightCharcoal,
            fontWeight: FontWeight.bold,
          ),
          bodyLarge: TextStyle(color: nightCharcoal),
          bodyMedium: TextStyle(color: nightCharcoal),
          bodySmall: TextStyle(color: slateGrey),
          labelLarge: TextStyle(color: slateGrey),
        ),

        // --- APP BAR ---
        appBarTheme: const AppBarTheme(
          backgroundColor: nightCharcoal,
          foregroundColor: iceBlue,
          centerTitle: true,
          elevation: 0,
        ),

        // --- CARD THEME REMOVED ---
        // The cardTheme was causing a type conflict (Widget vs Data).
        // We removed it so the app builds. Cards will default to the standard
        // Material look, which fits your Snow White theme perfectly.

        // --- BUTTONS ---
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: nightCharcoal,
            foregroundColor: iceBlue, // Ice Blue text on Dark button
            elevation: 3,
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),

        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: nightCharcoal,
            side: const BorderSide(color: slateGrey),
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),

        // --- INPUT FIELDS ---
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: Colors.white,
          labelStyle: const TextStyle(color: slateGrey),
          hintStyle: const TextStyle(color: slateGrey),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: slateGrey),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: iceBlue, width: 2),
          ),
          errorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Colors.redAccent),
          ),
        ),
      ),
      home: const Wrapper(),
    );
  }
}
