import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // The file generated by flutterfire

// 2. Make your main function async
void main() async {
  // 3. Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 4. Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 5. Run your app
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false, // Hides the "debug" banner
      title: 'FYP Hub',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
        ), // Changed seed color
        useMaterial3: true,
      ),
      // This is a temporary placeholder
      home: const Scaffold(body: Center(child: Text('Firebase Connected!'))),
    );
  }
}
