// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // The file generated by flutterfire
// import 'package:fyp_hub/screens/wrapper.dart';

// // 2. Make your main function async
// void main() async {
//   // 3. Ensure Flutter is initialized
//   WidgetsFlutterBinding.ensureInitialized();

//   // 4. Initialize Firebase
//   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

//   // 5. Run your app
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       debugShowCheckedModeBanner: false, // Hides the "debug" banner
//       title: 'FYP Hub',
//       theme: ThemeData(
//         brightness: Brightness.dark, // Tell the app it's a dark theme
//         colorScheme: ColorScheme.fromSeed(
//           seedColor: Colors.blue,
//           brightness: Brightness.dark, // Use a dark color scheme
//         ),
//         useMaterial3: true,
//       ),
//       // This is a temporary placeholder
//       home: const Wrapper(),
//     );
//   }
// }

// TEMPORARY MAIN.DART TO BYPASS LOGIN CHECKS
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; 

// 1. IMPORT YOUR SCREEN
import 'package:fyp_hub/screens/home/student_home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. We keep Firebase init so the app doesn't crash
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FYP Hub',
      theme: ThemeData(
        brightness: Brightness.dark, 
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
      // 3. THE HACK: 
      // Instead of 'Wrapper()', we force it to go to 'StudentHomeScreen'.
      // This bypasses Login checks completely.
      home: const StudentHomeScreen(),
    );
  }
}